#PACKAGE_PIN
# set_property  -dict {PACKAGE_PIN L16  IOSTANDARD LVCMOS33} [get_ports ledb_trx1  ]
# set_property  -dict {PACKAGE_PIN M17  IOSTANDARD LVCMOS33} [get_ports ledg_trx1  ]
# set_property  -dict {PACKAGE_PIN K19  IOSTANDARD LVCMOS33} [get_ports ledr_trx1  ]
# set_property  -dict {PACKAGE_PIN M20  IOSTANDARD LVCMOS33} [get_ports ledb_trx2  ]
# set_property  -dict {PACKAGE_PIN M19  IOSTANDARD LVCMOS33} [get_ports ledg_trx2  ]
# set_property  -dict {PACKAGE_PIN M18  IOSTANDARD LVCMOS33} [get_ports ledr_trx2  ]
#ad9361
set_property  -dict {PACKAGE_PIN P18  IOSTANDARD LVCMOS25} [get_ports  spi_csn      ]
set_property  -dict {PACKAGE_PIN R14  IOSTANDARD LVCMOS25} [get_ports  spi_clk      ]
set_property  -dict {PACKAGE_PIN P15  IOSTANDARD LVCMOS25} [get_ports  spi_mosi     ]
set_property  -dict {PACKAGE_PIN R19  IOSTANDARD LVCMOS25} [get_ports  spi_miso     ]
set_property  -dict {PACKAGE_PIN P16  IOSTANDARD LVCMOS25} [get_ports  en_agc       ]
set_property  -dict {PACKAGE_PIN R18  IOSTANDARD LVCMOS25} [get_ports  enable       ]
set_property  -dict {PACKAGE_PIN N17  IOSTANDARD LVCMOS25} [get_ports  resetb       ]
set_property  -dict {PACKAGE_PIN P14  IOSTANDARD LVCMOS25} [get_ports  txnrx        ]
set_property  -dict {PACKAGE_PIN U20  IOSTANDARD LVCMOS25} [get_ports  sync_in      ]
# set_property  -dict {PACKAGE_PIN   IOSTANDARD LVCMOS18} [get_ports  clk_out      ]
set_property  -dict {PACKAGE_PIN T10  IOSTANDARD LVCMOS25} [get_ports  ctrl_in[0]   ]
set_property  -dict {PACKAGE_PIN Y12  IOSTANDARD LVCMOS33} [get_ports  ctrl_in[1]   ]
set_property  -dict {PACKAGE_PIN Y13  IOSTANDARD LVCMOS33} [get_ports  ctrl_in[2]   ]
set_property  -dict {PACKAGE_PIN V11  IOSTANDARD LVCMOS33} [get_ports  ctrl_in[3]   ]

set_property  -dict {PACKAGE_PIN C20  IOSTANDARD LVCMOS33} [get_ports  bandsel_rx1_b ]
set_property  -dict {PACKAGE_PIN A20  IOSTANDARD LVCMOS33} [get_ports  bandsel_rx2_a ]
set_property  -dict {PACKAGE_PIN G14  IOSTANDARD LVCMOS33} [get_ports  bandsel_rx1_a ]
set_property  -dict {PACKAGE_PIN E17  IOSTANDARD LVCMOS33} [get_ports  bandsel_rx2_b ]
set_property  -dict {PACKAGE_PIN B20  IOSTANDARD LVCMOS33} [get_ports  bandsel_tx1_a ]
set_property  -dict {PACKAGE_PIN B19  IOSTANDARD LVCMOS33} [get_ports  bandsel_tx1_b ]
set_property  -dict {PACKAGE_PIN D18  IOSTANDARD LVCMOS33} [get_ports  bandsel_tx2_a ]
set_property  -dict {PACKAGE_PIN D19  IOSTANDARD LVCMOS33} [get_ports  bandsel_tx2_b ]

#set_property  -dict {PACKAGE_PIN Y6   IOSTANDARD LVCMOS25} [get_ports  ctrl_out[0]  ]
#set_property  -dict {PACKAGE_PIN U10  IOSTANDARD LVCMOS25} [get_ports  ctrl_out[1]  ]
#set_property  -dict {PACKAGE_PIN Y7   IOSTANDARD LVCMOS25} [get_ports  ctrl_out[2]  ]
#set_property  -dict {PACKAGE_PIN Y9   IOSTANDARD LVCMOS25} [get_ports  ctrl_out[3]  ]
#set_property  -dict {PACKAGE_PIN U7   IOSTANDARD LVCMOS25} [get_ports  ctrl_out[4]  ]
#set_property  -dict {PACKAGE_PIN V7   IOSTANDARD LVCMOS25} [get_ports  ctrl_out[5]  ]
#set_property  -dict {PACKAGE_PIN V5   IOSTANDARD LVCMOS25} [get_ports  ctrl_out[6]  ]
#set_property  -dict {PACKAGE_PIN T9   IOSTANDARD LVCMOS25} [get_ports  ctrl_out[7]  ]
#eagleGR
# set_property  -dict {PACKAGE_PIN L20  IOSTANDARD LVCMOS33} [get_ports  fddtdd_sw    ]
# set_property  -dict {PACKAGE_PIN L19  IOSTANDARD LVCMOS33} [get_ports  fddtdd_sw_n  ]
# set_property  -dict {PACKAGE_PIN F17  IOSTANDARD LVCMOS33} [get_ports  trx_sw       ]
# set_property  -dict {PACKAGE_PIN J19  IOSTANDARD LVCMOS33} [get_ports  trx_sw_n     ]

set_property  -dict {PACKAGE_PIN P19  IOSTANDARD LVDS_25 } [get_ports  tx_clk_out_n     ]
set_property  -dict {PACKAGE_PIN N18  IOSTANDARD LVDS_25 } [get_ports  tx_clk_out_p     ]
set_property  -dict {PACKAGE_PIN Y14  IOSTANDARD LVDS_25 } [get_ports  tx_data_out_n[0] ]
set_property  -dict {PACKAGE_PIN W14  IOSTANDARD LVDS_25 } [get_ports  tx_data_out_p[0] ]
set_property  -dict {PACKAGE_PIN U12  IOSTANDARD LVDS_25 } [get_ports  tx_data_out_n[1] ]
set_property  -dict {PACKAGE_PIN T12  IOSTANDARD LVDS_25 } [get_ports  tx_data_out_p[1] ]
set_property  -dict {PACKAGE_PIN U15  IOSTANDARD LVDS_25 } [get_ports  tx_data_out_n[2] ]
set_property  -dict {PACKAGE_PIN U14  IOSTANDARD LVDS_25 } [get_ports  tx_data_out_p[2] ]
set_property  -dict {PACKAGE_PIN U17  IOSTANDARD LVDS_25 } [get_ports  tx_data_out_n[3] ]
set_property  -dict {PACKAGE_PIN T16  IOSTANDARD LVDS_25 } [get_ports  tx_data_out_p[3] ]
set_property  -dict {PACKAGE_PIN W13  IOSTANDARD LVDS_25 } [get_ports  tx_data_out_n[4] ]
set_property  -dict {PACKAGE_PIN V12  IOSTANDARD LVDS_25 } [get_ports  tx_data_out_p[4] ]
set_property  -dict {PACKAGE_PIN W15  IOSTANDARD LVDS_25 } [get_ports  tx_data_out_n[5] ]
set_property  -dict {PACKAGE_PIN V15  IOSTANDARD LVDS_25 } [get_ports  tx_data_out_p[5] ]
set_property  -dict {PACKAGE_PIN Y17  IOSTANDARD LVDS_25 } [get_ports  tx_frame_out_n   ]
set_property  -dict {PACKAGE_PIN Y16  IOSTANDARD LVDS_25 } [get_ports  tx_frame_out_p   ]
set_property  -dict {PACKAGE_PIN P20  IOSTANDARD LVDS_25 } [get_ports  rx_clk_in_n      ]
set_property  -dict {PACKAGE_PIN N20  IOSTANDARD LVDS_25 } [get_ports  rx_clk_in_p      ]
set_property  -dict {PACKAGE_PIN Y19  IOSTANDARD LVDS_25 } [get_ports  rx_data_in_n[0]  ]
set_property  -dict {PACKAGE_PIN Y18  IOSTANDARD LVDS_25 } [get_ports  rx_data_in_p[0]  ]
set_property  -dict {PACKAGE_PIN V18  IOSTANDARD LVDS_25 } [get_ports  rx_data_in_n[1]  ]
set_property  -dict {PACKAGE_PIN V17  IOSTANDARD LVDS_25 } [get_ports  rx_data_in_p[1]  ]
set_property  -dict {PACKAGE_PIN W20  IOSTANDARD LVDS_25 } [get_ports  rx_data_in_n[2]  ]
set_property  -dict {PACKAGE_PIN V20  IOSTANDARD LVDS_25 } [get_ports  rx_data_in_p[2]  ]
set_property  -dict {PACKAGE_PIN R17  IOSTANDARD LVDS_25 } [get_ports  rx_data_in_n[3]  ]
set_property  -dict {PACKAGE_PIN R16  IOSTANDARD LVDS_25 } [get_ports  rx_data_in_p[3]  ]
set_property  -dict {PACKAGE_PIN W19  IOSTANDARD LVDS_25 } [get_ports  rx_data_in_n[4]  ]
set_property  -dict {PACKAGE_PIN W18  IOSTANDARD LVDS_25 } [get_ports  rx_data_in_p[4]  ]
set_property  -dict {PACKAGE_PIN W16  IOSTANDARD LVDS_25 } [get_ports  rx_data_in_n[5]  ]
set_property  -dict {PACKAGE_PIN V16  IOSTANDARD LVDS_25 } [get_ports  rx_data_in_p[5]  ]
set_property  -dict {PACKAGE_PIN U19  IOSTANDARD LVDS_25 } [get_ports  rx_frame_in_n    ]
set_property  -dict {PACKAGE_PIN U18  IOSTANDARD LVDS_25 } [get_ports  rx_frame_in_p    ]
